#!/usr/bin/env python3
"""Generate effects.py from Pokemon Showdown data.

Fetches ability, item, and move descriptions from Showdown's data files
and generates a complete effects database.

Usage:
    python scripts/generate_effects.py > src/data/effects.py
"""

import re
import httpx

BASE_URL = "https://raw.githubusercontent.com/smogon/pokemon-showdown/master/data/text"


def fetch_and_parse(endpoint: str) -> dict[str, str]:
    """Fetch TypeScript file and parse shortDesc entries."""
    url = f"{BASE_URL}/{endpoint}.ts"
    resp = httpx.get(url, timeout=30)
    resp.raise_for_status()
    text = resp.text

    # Parse entries with name and shortDesc
    pattern = r'^\t(\w+):\s*\{[^}]*?name:\s*"[^"]+"\s*,[^}]*?shortDesc:\s*"([^"]+)"'
    matches = re.findall(pattern, text, re.MULTILINE | re.DOTALL)

    # Filter out gen-specific overrides and normalize
    return {
        name.lower(): desc
        for name, desc in matches
        if not name.startswith("gen") and name != "noability"
    }


def simplify_description(desc: str) -> str:
    """Simplify descriptions for competitive context."""
    # Remove "This Pokemon's" prefix for brevity
    desc = re.sub(r"^This Pokemon'?s?\s+", "", desc)
    # Remove "holder's" for items
    desc = re.sub(r"^[Hh]older'?s?\s+", "", desc)
    # Capitalize first letter
    if desc:
        desc = desc[0].upper() + desc[1:]
    return desc


def main():
    print('"""Pokemon effects database - auto-generated from Pokemon Showdown data.')
    print("")
    print("Generated by scripts/generate_effects.py")
    print("Source: https://github.com/smogon/pokemon-showdown/tree/master/data/text")
    print('"""')
    print("")
    print("from typing import Optional")
    print("")

    # Fetch abilities
    print("# Fetching abilities...", file=__import__("sys").stderr)
    abilities = fetch_and_parse("abilities")
    print(f"# Found {len(abilities)} abilities", file=__import__("sys").stderr)

    print("")
    print(f"# {len(abilities)} abilities from Pokemon Showdown")
    print("ABILITY_EFFECTS: dict[str, str] = {")
    for name, desc in sorted(abilities.items()):
        simplified = simplify_description(desc)
        # Escape quotes in descriptions
        simplified = simplified.replace('"', '\\"')
        print(f'    "{name}": "{simplified}",')
    print("}")

    # Fetch items
    print("# Fetching items...", file=__import__("sys").stderr)
    items = fetch_and_parse("items")
    print(f"# Found {len(items)} items", file=__import__("sys").stderr)

    print("")
    print(f"# {len(items)} items from Pokemon Showdown")
    print("ITEM_EFFECTS: dict[str, str] = {")
    for name, desc in sorted(items.items()):
        simplified = simplify_description(desc)
        simplified = simplified.replace('"', '\\"')
        print(f'    "{name}": "{simplified}",')
    print("}")

    # Fetch moves
    print("# Fetching moves...", file=__import__("sys").stderr)
    moves = fetch_and_parse("moves")
    print(f"# Found {len(moves)} moves", file=__import__("sys").stderr)

    print("")
    print(f"# {len(moves)} moves from Pokemon Showdown")
    print("MOVE_EFFECTS: dict[str, str] = {")
    for name, desc in sorted(moves.items()):
        simplified = simplify_description(desc)
        simplified = simplified.replace('"', '\\"')
        print(f'    "{name}": "{simplified}",')
    print("}")

    # Add lookup functions
    print("")
    print("")
    print("def get_ability_effect(ability_id: str) -> Optional[str]:")
    print('    """Get effect description for an ability."""')
    print('    return ABILITY_EFFECTS.get(ability_id.lower().replace(" ", "").replace("-", ""))')
    print("")
    print("")
    print("def get_item_effect(item_id: str) -> Optional[str]:")
    print('    """Get effect description for an item."""')
    print('    return ITEM_EFFECTS.get(item_id.lower().replace(" ", "").replace("-", ""))')
    print("")
    print("")
    print("def get_move_effect(move_id: str) -> Optional[str]:")
    print('    """Get effect description for a move."""')
    print('    return MOVE_EFFECTS.get(move_id.lower().replace(" ", "").replace("-", ""))')


if __name__ == "__main__":
    main()
